import StyledComponentsRegistry from '@/style/lib/registry';
import Theme from '@/style/lib/theme';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable}`}>
        <QueryClientProvider client={queryClient}>
          <StyledComponentsRegistry>
            <Theme>{children}</Theme>
          </StyledComponentsRegistry>
        </QueryClientProvider>
      </body>
    </html>
  );
}
